// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: employee.proto
// Protobuf Java Version: 4.27.3

package com.employee.rest.api.development.grpc;

/**
 * Protobuf type {@code EmployeeResponse}
 */
public final class EmployeeResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:EmployeeResponse)
    EmployeeResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      EmployeeResponse.class.getName());
  }
  // Use EmployeeResponse.newBuilder() to construct.
  private EmployeeResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private EmployeeResponse() {
    employees_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.employee.rest.api.development.grpc.EmployeeOuterClass.internal_static_EmployeeResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.employee.rest.api.development.grpc.EmployeeOuterClass.internal_static_EmployeeResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.employee.rest.api.development.grpc.EmployeeResponse.class, com.employee.rest.api.development.grpc.EmployeeResponse.Builder.class);
  }

  public static final int EMPLOYEES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.employee.rest.api.development.grpc.Employee> employees_;
  /**
   * <code>repeated .Employee employees = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.employee.rest.api.development.grpc.Employee> getEmployeesList() {
    return employees_;
  }
  /**
   * <code>repeated .Employee employees = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.employee.rest.api.development.grpc.EmployeeOrBuilder> 
      getEmployeesOrBuilderList() {
    return employees_;
  }
  /**
   * <code>repeated .Employee employees = 1;</code>
   */
  @java.lang.Override
  public int getEmployeesCount() {
    return employees_.size();
  }
  /**
   * <code>repeated .Employee employees = 1;</code>
   */
  @java.lang.Override
  public com.employee.rest.api.development.grpc.Employee getEmployees(int index) {
    return employees_.get(index);
  }
  /**
   * <code>repeated .Employee employees = 1;</code>
   */
  @java.lang.Override
  public com.employee.rest.api.development.grpc.EmployeeOrBuilder getEmployeesOrBuilder(
      int index) {
    return employees_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < employees_.size(); i++) {
      output.writeMessage(1, employees_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < employees_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, employees_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.employee.rest.api.development.grpc.EmployeeResponse)) {
      return super.equals(obj);
    }
    com.employee.rest.api.development.grpc.EmployeeResponse other = (com.employee.rest.api.development.grpc.EmployeeResponse) obj;

    if (!getEmployeesList()
        .equals(other.getEmployeesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getEmployeesCount() > 0) {
      hash = (37 * hash) + EMPLOYEES_FIELD_NUMBER;
      hash = (53 * hash) + getEmployeesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.employee.rest.api.development.grpc.EmployeeResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.employee.rest.api.development.grpc.EmployeeResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.employee.rest.api.development.grpc.EmployeeResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.employee.rest.api.development.grpc.EmployeeResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.employee.rest.api.development.grpc.EmployeeResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.employee.rest.api.development.grpc.EmployeeResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.employee.rest.api.development.grpc.EmployeeResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.employee.rest.api.development.grpc.EmployeeResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.employee.rest.api.development.grpc.EmployeeResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.employee.rest.api.development.grpc.EmployeeResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.employee.rest.api.development.grpc.EmployeeResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.employee.rest.api.development.grpc.EmployeeResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.employee.rest.api.development.grpc.EmployeeResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code EmployeeResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EmployeeResponse)
      com.employee.rest.api.development.grpc.EmployeeResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.employee.rest.api.development.grpc.EmployeeOuterClass.internal_static_EmployeeResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.employee.rest.api.development.grpc.EmployeeOuterClass.internal_static_EmployeeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.employee.rest.api.development.grpc.EmployeeResponse.class, com.employee.rest.api.development.grpc.EmployeeResponse.Builder.class);
    }

    // Construct using com.employee.rest.api.development.grpc.EmployeeResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (employeesBuilder_ == null) {
        employees_ = java.util.Collections.emptyList();
      } else {
        employees_ = null;
        employeesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.employee.rest.api.development.grpc.EmployeeOuterClass.internal_static_EmployeeResponse_descriptor;
    }

    @java.lang.Override
    public com.employee.rest.api.development.grpc.EmployeeResponse getDefaultInstanceForType() {
      return com.employee.rest.api.development.grpc.EmployeeResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.employee.rest.api.development.grpc.EmployeeResponse build() {
      com.employee.rest.api.development.grpc.EmployeeResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.employee.rest.api.development.grpc.EmployeeResponse buildPartial() {
      com.employee.rest.api.development.grpc.EmployeeResponse result = new com.employee.rest.api.development.grpc.EmployeeResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.employee.rest.api.development.grpc.EmployeeResponse result) {
      if (employeesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          employees_ = java.util.Collections.unmodifiableList(employees_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.employees_ = employees_;
      } else {
        result.employees_ = employeesBuilder_.build();
      }
    }

    private void buildPartial0(com.employee.rest.api.development.grpc.EmployeeResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.employee.rest.api.development.grpc.EmployeeResponse) {
        return mergeFrom((com.employee.rest.api.development.grpc.EmployeeResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.employee.rest.api.development.grpc.EmployeeResponse other) {
      if (other == com.employee.rest.api.development.grpc.EmployeeResponse.getDefaultInstance()) return this;
      if (employeesBuilder_ == null) {
        if (!other.employees_.isEmpty()) {
          if (employees_.isEmpty()) {
            employees_ = other.employees_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEmployeesIsMutable();
            employees_.addAll(other.employees_);
          }
          onChanged();
        }
      } else {
        if (!other.employees_.isEmpty()) {
          if (employeesBuilder_.isEmpty()) {
            employeesBuilder_.dispose();
            employeesBuilder_ = null;
            employees_ = other.employees_;
            bitField0_ = (bitField0_ & ~0x00000001);
            employeesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getEmployeesFieldBuilder() : null;
          } else {
            employeesBuilder_.addAllMessages(other.employees_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.employee.rest.api.development.grpc.Employee m =
                  input.readMessage(
                      com.employee.rest.api.development.grpc.Employee.parser(),
                      extensionRegistry);
              if (employeesBuilder_ == null) {
                ensureEmployeesIsMutable();
                employees_.add(m);
              } else {
                employeesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.employee.rest.api.development.grpc.Employee> employees_ =
      java.util.Collections.emptyList();
    private void ensureEmployeesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        employees_ = new java.util.ArrayList<com.employee.rest.api.development.grpc.Employee>(employees_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.employee.rest.api.development.grpc.Employee, com.employee.rest.api.development.grpc.Employee.Builder, com.employee.rest.api.development.grpc.EmployeeOrBuilder> employeesBuilder_;

    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    public java.util.List<com.employee.rest.api.development.grpc.Employee> getEmployeesList() {
      if (employeesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(employees_);
      } else {
        return employeesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    public int getEmployeesCount() {
      if (employeesBuilder_ == null) {
        return employees_.size();
      } else {
        return employeesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    public com.employee.rest.api.development.grpc.Employee getEmployees(int index) {
      if (employeesBuilder_ == null) {
        return employees_.get(index);
      } else {
        return employeesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    public Builder setEmployees(
        int index, com.employee.rest.api.development.grpc.Employee value) {
      if (employeesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmployeesIsMutable();
        employees_.set(index, value);
        onChanged();
      } else {
        employeesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    public Builder setEmployees(
        int index, com.employee.rest.api.development.grpc.Employee.Builder builderForValue) {
      if (employeesBuilder_ == null) {
        ensureEmployeesIsMutable();
        employees_.set(index, builderForValue.build());
        onChanged();
      } else {
        employeesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    public Builder addEmployees(com.employee.rest.api.development.grpc.Employee value) {
      if (employeesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmployeesIsMutable();
        employees_.add(value);
        onChanged();
      } else {
        employeesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    public Builder addEmployees(
        int index, com.employee.rest.api.development.grpc.Employee value) {
      if (employeesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmployeesIsMutable();
        employees_.add(index, value);
        onChanged();
      } else {
        employeesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    public Builder addEmployees(
        com.employee.rest.api.development.grpc.Employee.Builder builderForValue) {
      if (employeesBuilder_ == null) {
        ensureEmployeesIsMutable();
        employees_.add(builderForValue.build());
        onChanged();
      } else {
        employeesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    public Builder addEmployees(
        int index, com.employee.rest.api.development.grpc.Employee.Builder builderForValue) {
      if (employeesBuilder_ == null) {
        ensureEmployeesIsMutable();
        employees_.add(index, builderForValue.build());
        onChanged();
      } else {
        employeesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    public Builder addAllEmployees(
        java.lang.Iterable<? extends com.employee.rest.api.development.grpc.Employee> values) {
      if (employeesBuilder_ == null) {
        ensureEmployeesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, employees_);
        onChanged();
      } else {
        employeesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    public Builder clearEmployees() {
      if (employeesBuilder_ == null) {
        employees_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        employeesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    public Builder removeEmployees(int index) {
      if (employeesBuilder_ == null) {
        ensureEmployeesIsMutable();
        employees_.remove(index);
        onChanged();
      } else {
        employeesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    public com.employee.rest.api.development.grpc.Employee.Builder getEmployeesBuilder(
        int index) {
      return getEmployeesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    public com.employee.rest.api.development.grpc.EmployeeOrBuilder getEmployeesOrBuilder(
        int index) {
      if (employeesBuilder_ == null) {
        return employees_.get(index);  } else {
        return employeesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    public java.util.List<? extends com.employee.rest.api.development.grpc.EmployeeOrBuilder> 
         getEmployeesOrBuilderList() {
      if (employeesBuilder_ != null) {
        return employeesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(employees_);
      }
    }
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    public com.employee.rest.api.development.grpc.Employee.Builder addEmployeesBuilder() {
      return getEmployeesFieldBuilder().addBuilder(
          com.employee.rest.api.development.grpc.Employee.getDefaultInstance());
    }
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    public com.employee.rest.api.development.grpc.Employee.Builder addEmployeesBuilder(
        int index) {
      return getEmployeesFieldBuilder().addBuilder(
          index, com.employee.rest.api.development.grpc.Employee.getDefaultInstance());
    }
    /**
     * <code>repeated .Employee employees = 1;</code>
     */
    public java.util.List<com.employee.rest.api.development.grpc.Employee.Builder> 
         getEmployeesBuilderList() {
      return getEmployeesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.employee.rest.api.development.grpc.Employee, com.employee.rest.api.development.grpc.Employee.Builder, com.employee.rest.api.development.grpc.EmployeeOrBuilder> 
        getEmployeesFieldBuilder() {
      if (employeesBuilder_ == null) {
        employeesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.employee.rest.api.development.grpc.Employee, com.employee.rest.api.development.grpc.Employee.Builder, com.employee.rest.api.development.grpc.EmployeeOrBuilder>(
                employees_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        employees_ = null;
      }
      return employeesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:EmployeeResponse)
  }

  // @@protoc_insertion_point(class_scope:EmployeeResponse)
  private static final com.employee.rest.api.development.grpc.EmployeeResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.employee.rest.api.development.grpc.EmployeeResponse();
  }

  public static com.employee.rest.api.development.grpc.EmployeeResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EmployeeResponse>
      PARSER = new com.google.protobuf.AbstractParser<EmployeeResponse>() {
    @java.lang.Override
    public EmployeeResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EmployeeResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EmployeeResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.employee.rest.api.development.grpc.EmployeeResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

