// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: employee.proto
// Protobuf Java Version: 4.27.3

package com.employee.rest.api.development.grpc;

public final class EmployeeOuterClass {
  private EmployeeOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      EmployeeOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Employee_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Employee_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmployeeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EmployeeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmployeeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EmployeeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016employee.proto\032\033google/protobuf/empty." +
      "proto\"]\n\010Employee\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 " +
      "\001(\t\022\023\n\013designation\030\003 \001(\t\022\016\n\006salary\030\004 \001(\001" +
      "\022\022\n\ndepartment\030\005 \001(\t\"\035\n\017EmployeeRequest\022" +
      "\n\n\002id\030\001 \001(\005\"0\n\020EmployeeResponse\022\034\n\templo" +
      "yees\030\001 \003(\0132\t.Employee2\225\002\n\017EmployeeServic" +
      "e\0220\n\017GetEmployeeById\022\020.EmployeeRequest\032\t" +
      ".Employee\"\000\022>\n\017GetAllEmployees\022\026.google." +
      "protobuf.Empty\032\021.EmployeeResponse\"\000\022(\n\016C" +
      "reateEmployee\022\t.Employee\032\t.Employee\"\000\022(\n" +
      "\016UpdateEmployee\022\t.Employee\032\t.Employee\"\000\022" +
      "<\n\016DeleteEmployee\022\020.EmployeeRequest\032\026.go" +
      "ogle.protobuf.Empty\"\000B*\n&com.employee.re" +
      "st.api.development.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_Employee_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Employee_descriptor,
        new java.lang.String[] { "Id", "Name", "Designation", "Salary", "Department", });
    internal_static_EmployeeRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EmployeeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_EmployeeRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_EmployeeResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_EmployeeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_EmployeeResponse_descriptor,
        new java.lang.String[] { "Employees", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
